# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuthenticationITEA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuthenticationITEA

pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'RealmSwift'
pod 'SwiftGifOrigin'
pod 'Kingfisher'
pod 'Firebase/Storage'
pod 'Alamofire', '~> 4.8.2'
pod 'AlamofireObjectMapper'

end
